### ISSUE TITLE
Inventory ylimääräisyys?

### ISSUE THREAD

**Issue by Embalistico** [Napalmu/text-based-rogue-like#6]
Miksi player.java-tiedostossa pelaajan oliolla on lähes duplikaatit inventory.java-tiedoston metodeista? Onko tarpeellista, että sama metodi kutsutaan ikään kuin kaksi kertaa (ensin pelaaja kutsuu esim. removeItem(), joka vain kutsuu inventory-oliolta removeItem()-metodin), vai olisiko järkevämpi/mahdollista pitää inventoryn metodit ihan sillä itsellään. Pelaajiahan on vain yksi, joten onko pelaaja-oliolla edes tarvetta omistaa inventory-oliota?

Muutoksia ei ole kommentoitu, joten voi olla, että ymmärrän asian väärin.

**Comment by andreiBe** [comment]
Joo voisin tehdä sillei et Playerillä on getInventory() metodi ja sit kutsutaan inventory olion metodeja. Aattelin laittaa inventoryn erikseen, koska pelaajaluokasta tulee varmaan aika iso niin aattelin jakaa koodia eri tiedostoihin.
